
package software1;

import java.awt.event.ActionListener;

public class AuthPopup extends javax.swing.JPanel {

    /**
     * Creates new form AuthPopup
     */
    public AuthPopup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        authenticpass = new javax.swing.JPasswordField();
        confirmPass = new javax.swing.JButton();
        AuthJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(229, 229, 229));

        authenticpass.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 24)); // NOI18N
        authenticpass.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        authenticpass.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        confirmPass.setText("Confirm");
        confirmPass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmPassActionPerformed(evt);
            }
        });

        AuthJLabel.setFont(new java.awt.Font("Source Sans Pro Light", 1, 24)); // NOI18N
        AuthJLabel.setForeground(new java.awt.Color(10, 64, 83));
        AuthJLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AuthJLabel.setText("Owner Authenticate");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(confirmPass))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(authenticpass)
                            .addComponent(AuthJLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(AuthJLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authenticpass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmPass)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmPassActionPerformed

    }//GEN-LAST:event_confirmPassActionPerformed
    protected char[] getPass() {
        return authenticpass.getPassword();
    }
    public void authenticate (ActionListener event){
        confirmPass.addActionListener(event);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AuthJLabel;
    private javax.swing.JPasswordField authenticpass;
    private javax.swing.JButton confirmPass;
    // End of variables declaration//GEN-END:variables
}
