/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package software1;

import glasspanepopup.GlassPanePopup;
import java.awt.event.ActionListener;

public class CancelOrder extends javax.swing.JPanel {

    /**
     * Creates new form CancelOrder
     */
    public CancelOrder() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cancelOrderLabel = new javax.swing.JLabel();
        cancelbackbtn = new javax.swing.JButton();
        cancelOrderbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(229, 229, 229));

        cancelOrderLabel.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 24)); // NOI18N
        cancelOrderLabel.setForeground(new java.awt.Color(34, 73, 87));
        cancelOrderLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cancelOrderLabel.setText("Cancel Order?");

        cancelbackbtn.setBackground(new java.awt.Color(140, 208, 218));
        cancelbackbtn.setForeground(new java.awt.Color(34, 73, 87));
        cancelbackbtn.setText("Back");
        cancelbackbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbackbtnActionPerformed(evt);
            }
        });

        cancelOrderbtn.setBackground(new java.awt.Color(35, 86, 108));
        cancelOrderbtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelOrderbtn.setText("Cancel");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(cancelbackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(cancelOrderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addGap(101, 101, 101)
                .addComponent(cancelOrderLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(cancelOrderLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelbackbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelOrderbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbackbtnActionPerformed
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_cancelbackbtnActionPerformed
    public void cancelOrder(ActionListener event){
        cancelOrderbtn.addActionListener(event);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cancelOrderLabel;
    private javax.swing.JButton cancelOrderbtn;
    private javax.swing.JButton cancelbackbtn;
    // End of variables declaration//GEN-END:variables
}
