
package software1;

import glasspanepopup.GlassPanePopup;
import java.awt.event.ActionListener;
import java.util.Date;

public class ComboBoxEditPopup extends javax.swing.JPanel {
    private final Object id;
    private final String colname;
    
    public ComboBoxEditPopup(String title, String subtitle, Long orderID, boolean s) {
        initComponents();
        this.id = orderID;
        this.colname = title;
        lbltitle.setText(title);
        lblsubtitle.setText(subtitle);
        box.addItem("Not Fully Paid");
        box.addItem("Fully Paid");
        if (s) box.setSelectedIndex(1); // index 1 is true
    }
    public ComboBoxEditPopup(String title, String subtitle, Long orderID, String s) { // For status
        initComponents();
        this.id = orderID;
        this.colname = title;
        lbltitle.setText(title);
        lblsubtitle.setText(subtitle);
        box.addItem("Pending");
        box.addItem("Ongoing");
        box.addItem("Complete");
        box.setSelectedItem(s);
    }

    ComboBoxEditPopup(String title, String subtitle, String username, String s) {
        initComponents();
        this.id = username;
        this.colname = title;
        lbltitle.setText(title);
        lblsubtitle.setText(subtitle);
        box.addItem("staff");
        box.addItem("delivery");
        box.setSelectedItem(s);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbltitle = new javax.swing.JLabel();
        lblsubtitle = new javax.swing.JLabel();
        cancelbtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        box = new javax.swing.JComboBox<>();

        setBackground(new java.awt.Color(229, 229, 229));

        lbltitle.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 24)); // NOI18N
        lbltitle.setForeground(new java.awt.Color(34, 73, 87));
        lbltitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbltitle.setText("<title>");
        lbltitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblsubtitle.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 12)); // NOI18N
        lblsubtitle.setForeground(new java.awt.Color(34, 73, 87));
        lblsubtitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblsubtitle.setText("<subtitle>");

        cancelbtn.setBackground(new java.awt.Color(235, 89, 89));
        cancelbtn.setText("Cancel");
        cancelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelbtnActionPerformed(evt);
            }
        });

        savebtn.setBackground(new java.awt.Color(34, 73, 87));
        savebtn.setForeground(new java.awt.Color(255, 255, 255));
        savebtn.setText("Save");

        box.setLightWeightPopupEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbltitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(lblsubtitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                                .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(box, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 45, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(lbltitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblsubtitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(box, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cancelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelbtnActionPerformed
        GlassPanePopup.closePopupLast();
    }//GEN-LAST:event_cancelbtnActionPerformed
    
    public void save(ActionListener al) {
        savebtn.addActionListener(al);
        savebtn.addActionListener((ActionListener) -> {
            Database db = new Database();
            switch (colname) {
                case "FullyPaid" -> db.updateFullyPaid((Long)id, box.getSelectedIndex()==1);
                case "DeliveryStatus" -> db.updateDeliveryStatus((Long)id, box.getSelectedIndex());
                case "Role" -> db.updateRole((String) id, (String) box.getSelectedItem());
            }
            GlassPanePopup.closePopupAll();
            db.closeConnection();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> box;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelbtn;
    private javax.swing.JLabel lblsubtitle;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JButton savebtn;
    // End of variables declaration//GEN-END:variables
}
