
package software1;

import java.awt.event.ActionListener;

public class DeliveryUpdatePopup extends javax.swing.JPanel {

    /**
     * Creates new form DeliveryUpdatePopup
     */
    public DeliveryUpdatePopup() {
        initComponents();
    }
    
    public void fail (ActionListener evt) {
        faildeliverybtn.addActionListener(evt);
    }
    public void complete (ActionListener evt) {
        completedeliverybtn.addActionListener(evt);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        faildeliverybtn = new javax.swing.JButton();
        completedeliverybtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(229, 229, 229));

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 73, 87));
        jLabel1.setText("Update Delivery Progress?");

        faildeliverybtn.setBackground(new java.awt.Color(235, 89, 89));
        faildeliverybtn.setForeground(new java.awt.Color(34, 73, 87));
        faildeliverybtn.setText("Failed");

        completedeliverybtn.setBackground(new java.awt.Color(140, 208, 218));
        completedeliverybtn.setForeground(new java.awt.Color(34, 73, 87));
        completedeliverybtn.setText("Complete");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(faildeliverybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(completedeliverybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(73, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(completedeliverybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(faildeliverybtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton completedeliverybtn;
    private javax.swing.JButton faildeliverybtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
