/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package software1;

import java.sql.SQLException;
import java.util.Arrays;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author 97433
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        userfield = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        passfield = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QNB Admin");
        setBackground(new java.awt.Color(229, 229, 229));

        jPanel7.setBackground(new java.awt.Color(229, 229, 229));
        jPanel7.setPreferredSize(new java.awt.Dimension(775, 440));

        jPanel8.setBackground(new java.awt.Color(229, 229, 229));
        jPanel8.setPreferredSize(new java.awt.Dimension(784, 138));

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Light", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(10, 64, 83));
        jLabel1.setText("QBC");

        jLabel5.setForeground(new java.awt.Color(10, 64, 83));
        jLabel5.setText("Log in to start your water transactions!");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(294, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(288, 288, 288))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(344, 344, 344))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5))
        );

        jPanel7.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(229, 229, 229));
        jPanel9.setPreferredSize(new java.awt.Dimension(775, 170));

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));
        jPanel1.setPreferredSize(new java.awt.Dimension(400, 45));
        jPanel1.setLayout(new java.awt.BorderLayout());

        userfield.setBackground(new java.awt.Color(23, 90, 115));
        userfield.setForeground(new java.awt.Color(255, 255, 255));
        userfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userfieldActionPerformed(evt);
            }
        });
        jPanel1.add(userfield, java.awt.BorderLayout.CENTER);

        jLabel2.setForeground(new java.awt.Color(10, 64, 83));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel9.add(jPanel1);

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));
        jPanel2.setPreferredSize(new java.awt.Dimension(400, 45));
        jPanel2.setLayout(new java.awt.BorderLayout());

        passfield.setForeground(new java.awt.Color(10, 64, 83));
        passfield.setText("Password");
        jPanel2.add(passfield, java.awt.BorderLayout.PAGE_START);

        jPasswordField1.setBackground(new java.awt.Color(23, 90, 115));
        jPasswordField1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jPasswordField1, java.awt.BorderLayout.CENTER);

        jPanel9.add(jPanel2);

        jPanel3.setBackground(new java.awt.Color(229, 229, 229));
        jPanel3.setPreferredSize(new java.awt.Dimension(400, 45));
        jPanel3.setLayout(new java.awt.BorderLayout());

        jCheckBox1.setForeground(new java.awt.Color(10, 64, 83));
        jCheckBox1.setText("Remember me");
        jPanel3.add(jCheckBox1, java.awt.BorderLayout.CENTER);

        jLabel4.setForeground(new java.awt.Color(10, 64, 83));
        jLabel4.setText("Forgot Password?");
        jPanel3.add(jLabel4, java.awt.BorderLayout.LINE_END);

        login.setBackground(new java.awt.Color(66, 155, 186));
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        jPanel3.add(login, java.awt.BorderLayout.PAGE_END);

        jPanel9.add(jPanel3);

        jPanel7.add(jPanel9);

        jPanel10.setBackground(new java.awt.Color(229, 229, 229));
        jPanel10.setPreferredSize(new java.awt.Dimension(784, 135));

        jLabel6.setPreferredSize(new java.awt.Dimension(775, 170));
        jPanel10.add(jLabel6);

        jPanel7.add(jPanel10);

        getContentPane().add(jPanel7, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userfieldActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        System.out.println("login button clicked");
        String name = userfield.getText();
        String pass = jPasswordField1.getText(); // set each char to 0 after for security
        
        System.out.println("name: " + name);
        System.out.println("pass: " + pass);
        // Database details
        Database db;
        db = new Database(
                "com.mysql.cj.jdbc.Driver",
                "root",
                "root",
                "jdbc:mysql://localhost:3306/db_qnb"
        );
        if (db.verifyUser(name, pass)) {
            System.out.println("VERIFY SUCCESS");
            Main main = new Main();
            main.setVisible(true);
            this.dispose();
        }
        else {
            System.out.println("WRONG USERNAME OR PASSWORD");
        }
        db = null;
        System.out.println("end");
    }//GEN-LAST:event_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton login;
    private javax.swing.JLabel passfield;
    private javax.swing.JTextField userfield;
    // End of variables declaration//GEN-END:variables
}
