/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package software1;

/**
 *
 * @author 97433
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Invoices
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        popupmenu1 = new javax.swing.JPopupMenu();
        maintabs = new javax.swing.JPanel();
        qnb = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        invoicetab = new javax.swing.JPanel();
        invoicebtn = new javax.swing.JLabel();
        transactab = new javax.swing.JPanel();
        transacbtn = new javax.swing.JLabel();
        delivertab = new javax.swing.JPanel();
        deliverbtn = new javax.swing.JLabel();
        authentictab = new javax.swing.JPanel();
        authenticbtn = new javax.swing.JLabel();
        signout = new javax.swing.JPanel();
        signoutbtn = new javax.swing.JLabel();
        tabcontent = new javax.swing.JPanel();
        invoices = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        productimg = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        productdesc = new javax.swing.JLabel();
        productname1 = new javax.swing.JLabel();
        productqty = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        productprice = new javax.swing.JLabel();
        productselect = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        form = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        fnamefield = new javax.swing.JTextField();
        lnamefield = new javax.swing.JTextField();
        housefield = new javax.swing.JTextField();
        brgyfield = new javax.swing.JTextField();
        cityfield = new javax.swing.JTextField();
        mobilefield = new javax.swing.JTextField();
        radiowalkin = new javax.swing.JRadioButton();
        radiodeliver = new javax.swing.JRadioButton();
        submitform = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        productimg1 = new javax.swing.JLabel();
        pendingtransac = new javax.swing.JPanel();
        completebtn1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        pendingtransactbl = new javax.swing.JTable();
        pendingbtn1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        generatebtn = new javax.swing.JButton();
        editmodule1 = new javax.swing.JButton();
        completetransac = new javax.swing.JPanel();
        completebtn2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        pendingtransactbl1 = new javax.swing.JTable();
        pendingbtn2 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        generatebtn1 = new javax.swing.JButton();
        editmodule2 = new javax.swing.JButton();
        pendingdeliver = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        pendingdelivertbl = new javax.swing.JTable();
        pendingbtn3 = new javax.swing.JLabel();
        completebtn3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        generatebtn2 = new javax.swing.JButton();
        editmodule3 = new javax.swing.JButton();
        completedeliver = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        pendingdelivertbl1 = new javax.swing.JTable();
        pendingbtn4 = new javax.swing.JLabel();
        completebtn4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        generatebtn3 = new javax.swing.JButton();
        editmodule4 = new javax.swing.JButton();
        authenticate = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        authpassbtn = new javax.swing.JButton();
        authpass = new javax.swing.JPasswordField();
        authreports = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        genreport1 = new javax.swing.JButton();
        genreport2 = new javax.swing.JButton();
        genreport3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("QNB System");
        setBackground(new java.awt.Color(255, 255, 255));

        maintabs.setBackground(new java.awt.Color(255, 255, 255));
        maintabs.setPreferredSize(new java.awt.Dimension(1250, 75));

        qnb.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(10, 64, 83));
        jLabel1.setText("QNB");
        jLabel1.setPreferredSize(new java.awt.Dimension(175, 70));

        javax.swing.GroupLayout qnbLayout = new javax.swing.GroupLayout(qnb);
        qnb.setLayout(qnbLayout);
        qnbLayout.setHorizontalGroup(
            qnbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qnbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        qnbLayout.setVerticalGroup(
            qnbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(qnbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        maintabs.add(qnb);

        invoicetab.setBackground(new java.awt.Color(255, 255, 255));

        invoicebtn.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 18)); // NOI18N
        invoicebtn.setForeground(new java.awt.Color(10, 64, 83));
        invoicebtn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        invoicebtn.setText("Invoices");
        invoicebtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        invoicebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        invoicebtn.setPreferredSize(new java.awt.Dimension(175, 70));
        invoicebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                invoicebtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout invoicetabLayout = new javax.swing.GroupLayout(invoicetab);
        invoicetab.setLayout(invoicetabLayout);
        invoicetabLayout.setHorizontalGroup(
            invoicetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicetabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(invoicebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        invoicetabLayout.setVerticalGroup(
            invoicetabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(invoicetabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(invoicebtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        maintabs.add(invoicetab);

        transactab.setBackground(new java.awt.Color(255, 255, 255));

        transacbtn.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        transacbtn.setForeground(new java.awt.Color(10, 64, 83));
        transacbtn.setText("Transactions");
        transacbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        transacbtn.setPreferredSize(new java.awt.Dimension(175, 70));

        javax.swing.GroupLayout transactabLayout = new javax.swing.GroupLayout(transactab);
        transactab.setLayout(transactabLayout);
        transactabLayout.setHorizontalGroup(
            transactabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transacbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        transactabLayout.setVerticalGroup(
            transactabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transactabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(transacbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        maintabs.add(transactab);

        delivertab.setBackground(new java.awt.Color(255, 255, 255));

        deliverbtn.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        deliverbtn.setForeground(new java.awt.Color(10, 64, 83));
        deliverbtn.setText("Deliveries");
        deliverbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        deliverbtn.setPreferredSize(new java.awt.Dimension(175, 70));

        javax.swing.GroupLayout delivertabLayout = new javax.swing.GroupLayout(delivertab);
        delivertab.setLayout(delivertabLayout);
        delivertabLayout.setHorizontalGroup(
            delivertabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delivertabLayout.createSequentialGroup()
                .addComponent(deliverbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );
        delivertabLayout.setVerticalGroup(
            delivertabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(delivertabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(deliverbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        maintabs.add(delivertab);

        authentictab.setBackground(new java.awt.Color(255, 255, 255));

        authenticbtn.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        authenticbtn.setForeground(new java.awt.Color(10, 64, 83));
        authenticbtn.setText("Authenticate");
        authenticbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        authenticbtn.setPreferredSize(new java.awt.Dimension(175, 70));

        javax.swing.GroupLayout authentictabLayout = new javax.swing.GroupLayout(authentictab);
        authentictab.setLayout(authentictabLayout);
        authentictabLayout.setHorizontalGroup(
            authentictabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authentictabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(authenticbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(117, Short.MAX_VALUE))
        );
        authentictabLayout.setVerticalGroup(
            authentictabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authentictabLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(authenticbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        maintabs.add(authentictab);

        signout.setBackground(new java.awt.Color(255, 255, 255));

        signoutbtn.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        signoutbtn.setForeground(new java.awt.Color(10, 64, 83));
        signoutbtn.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        signoutbtn.setText("Sign out");
        signoutbtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        signoutbtn.setPreferredSize(new java.awt.Dimension(175, 70));

        javax.swing.GroupLayout signoutLayout = new javax.swing.GroupLayout(signout);
        signout.setLayout(signoutLayout);
        signoutLayout.setHorizontalGroup(
            signoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, signoutLayout.createSequentialGroup()
                .addGap(0, 56, Short.MAX_VALUE)
                .addComponent(signoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        signoutLayout.setVerticalGroup(
            signoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(signoutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(signoutbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        maintabs.add(signout);

        getContentPane().add(maintabs, java.awt.BorderLayout.PAGE_START);

        tabcontent.setBackground(new java.awt.Color(255, 255, 255));
        tabcontent.setPreferredSize(new java.awt.Dimension(1250, 675));
        tabcontent.setLayout(new java.awt.CardLayout());

        invoices.setBackground(new java.awt.Color(255, 255, 255));
        invoices.setPreferredSize(new java.awt.Dimension(1250, 625));
        invoices.setLayout(new javax.swing.BoxLayout(invoices, javax.swing.BoxLayout.LINE_AXIS));

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));

        productimg.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productimg.setText("img");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(103, 143));

        jLabel10.setText("jLabel10");
        jPanel2.add(jLabel10);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(productimg, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(productimg, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 132, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        invoices.add(jPanel14);

        jPanel12.setBackground(new java.awt.Color(229, 229, 229));
        jPanel12.setPreferredSize(new java.awt.Dimension(627, 675));

        productdesc.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        productdesc.setForeground(new java.awt.Color(10, 64, 83));
        productdesc.setText("Product Decription");
        productdesc.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        productdesc.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        productname1.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 48)); // NOI18N
        productname1.setForeground(new java.awt.Color(10, 64, 83));
        productname1.setText("Product");

        productqty.setModel(new javax.swing.SpinnerNumberModel(1, null, null, 1));

        jLabel8.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel8.setText(" ");

        productprice.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        productprice.setForeground(new java.awt.Color(10, 64, 83));
        productprice.setText("Price:");

        productselect.setBackground(new java.awt.Color(66, 155, 186));
        productselect.setForeground(new java.awt.Color(0, 0, 0));
        productselect.setText("Select");
        productselect.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(66, 155, 186), 1, true));
        productselect.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jButton1.setBackground(new java.awt.Color(10, 64, 83));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Order");
        jButton1.setComponentPopupMenu(popupmenu1);

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));

        jLabel9.setText("jLabel9");
        jPanel1.add(jLabel9);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(productprice)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(productqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productname1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(productselect, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(productdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(165, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(productname1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(productdesc, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(productqty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(productprice))
                .addGap(18, 18, 18)
                .addComponent(productselect, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE))
        );

        invoices.add(jPanel12);

        tabcontent.add(invoices, "card3");
        invoices.getAccessibleContext().setAccessibleName("Transactions");

        form.setBackground(new java.awt.Color(255, 255, 255));
        form.setPreferredSize(new java.awt.Dimension(1250, 625));
        form.setLayout(new javax.swing.BoxLayout(form, javax.swing.BoxLayout.LINE_AXIS));

        jPanel16.setBackground(new java.awt.Color(229, 229, 229));
        jPanel16.setPreferredSize(new java.awt.Dimension(623, 625));

        jLabel11.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(34, 73, 87));
        jLabel11.setText("Last name");

        jLabel12.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(34, 73, 87));
        jLabel12.setText("First name");

        jLabel13.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(34, 73, 87));
        jLabel13.setText("Barangay/Municipality");

        jLabel14.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(34, 73, 87));
        jLabel14.setText("House/Unit no., Street");

        jLabel15.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(34, 73, 87));
        jLabel15.setText("Mobile no.");

        jLabel16.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(34, 73, 87));
        jLabel16.setText("City");

        fnamefield.setBackground(new java.awt.Color(255, 255, 255));
        fnamefield.setForeground(new java.awt.Color(0, 0, 0));

        lnamefield.setBackground(new java.awt.Color(255, 255, 255));
        lnamefield.setForeground(new java.awt.Color(0, 0, 0));

        housefield.setBackground(new java.awt.Color(255, 255, 255));
        housefield.setForeground(new java.awt.Color(0, 0, 0));

        brgyfield.setBackground(new java.awt.Color(255, 255, 255));
        brgyfield.setForeground(new java.awt.Color(0, 0, 0));

        cityfield.setBackground(new java.awt.Color(255, 255, 255));
        cityfield.setForeground(new java.awt.Color(0, 0, 0));

        mobilefield.setBackground(new java.awt.Color(255, 255, 255));
        mobilefield.setForeground(new java.awt.Color(0, 0, 0));

        buttonGroup1.add(radiowalkin);
        radiowalkin.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        radiowalkin.setForeground(new java.awt.Color(34, 73, 87));
        radiowalkin.setText("for Walk-in");

        buttonGroup1.add(radiodeliver);
        radiodeliver.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        radiodeliver.setForeground(new java.awt.Color(34, 73, 87));
        radiodeliver.setText("for Delivery");

        submitform.setBackground(new java.awt.Color(140, 208, 218));
        submitform.setForeground(new java.awt.Color(34, 73, 87));
        submitform.setText("Submit");

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(housefield)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(115, 115, 115)
                        .addComponent(jLabel11))
                    .addComponent(jLabel14)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(brgyfield, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cityfield))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel16))
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel15)
                    .addComponent(mobilefield)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(radiodeliver, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radiowalkin, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(submitform, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel11))
                .addGap(5, 5, 5)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lnamefield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(housefield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(brgyfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityfield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mobilefield, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(radiowalkin)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radiodeliver))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel16Layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(submitform, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        form.add(jPanel16);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));

        productimg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        productimg1.setText("img");

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(productimg1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(168, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(productimg1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(275, Short.MAX_VALUE))
        );

        form.add(jPanel15);

        tabcontent.add(form, "card4");
        form.getAccessibleContext().setAccessibleName("Deliveries");

        pendingtransac.setBackground(new java.awt.Color(255, 255, 255));
        pendingtransac.setPreferredSize(new java.awt.Dimension(1250, 625));

        completebtn1.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 36)); // NOI18N
        completebtn1.setForeground(new java.awt.Color(10, 64, 83));
        completebtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completebtn1.setText("Completed");

        pendingtransactbl.setBackground(new java.awt.Color(229, 229, 229));
        pendingtransactbl.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        pendingtransactbl.setForeground(new java.awt.Color(10, 64, 83));
        pendingtransactbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Item/QTY", "Customer ID", "Name", "Address", "Price", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(pendingtransactbl);

        pendingbtn1.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 36)); // NOI18N
        pendingbtn1.setForeground(new java.awt.Color(10, 64, 83));
        pendingbtn1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingbtn1.setText("Pending");

        jComboBox1.setBackground(new java.awt.Color(10, 64, 83));
        jComboBox1.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 12)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox1.setMaximumRowCount(3);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Orders", "Walk-ins", "Deliveries" }));

        generatebtn.setBackground(new java.awt.Color(140, 208, 218));
        generatebtn.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 12)); // NOI18N
        generatebtn.setForeground(new java.awt.Color(34, 73, 87));
        generatebtn.setText("Generate");

        editmodule1.setBackground(new java.awt.Color(140, 208, 218));
        editmodule1.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 12)); // NOI18N
        editmodule1.setForeground(new java.awt.Color(34, 73, 87));
        editmodule1.setText("Edit Module");

        javax.swing.GroupLayout pendingtransacLayout = new javax.swing.GroupLayout(pendingtransac);
        pendingtransac.setLayout(pendingtransacLayout);
        pendingtransacLayout.setHorizontalGroup(
            pendingtransacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingtransacLayout.createSequentialGroup()
                .addGroup(pendingtransacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pendingtransacLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(pendingbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(completebtn1))
                    .addGroup(pendingtransacLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(pendingtransacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pendingtransacLayout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generatebtn)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editmodule1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        pendingtransacLayout.setVerticalGroup(
            pendingtransacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingtransacLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pendingtransacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(completebtn1)
                    .addComponent(pendingbtn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pendingtransacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generatebtn)
                    .addComponent(editmodule1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        tabcontent.add(pendingtransac, "card5");
        pendingtransac.getAccessibleContext().setAccessibleName("Authenticate");

        completetransac.setBackground(new java.awt.Color(255, 255, 255));
        completetransac.setPreferredSize(new java.awt.Dimension(1250, 625));

        completebtn2.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 36)); // NOI18N
        completebtn2.setForeground(new java.awt.Color(10, 64, 83));
        completebtn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completebtn2.setText("Completed");

        pendingtransactbl1.setBackground(new java.awt.Color(229, 229, 229));
        pendingtransactbl1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(229, 229, 229)));
        pendingtransactbl1.setForeground(new java.awt.Color(10, 64, 83));
        pendingtransactbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Item/QTY", "Customer ID", "Name", "Address", "Price", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(pendingtransactbl1);

        pendingbtn2.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 36)); // NOI18N
        pendingbtn2.setForeground(new java.awt.Color(10, 64, 83));
        pendingbtn2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingbtn2.setText("Pending");

        jComboBox3.setBackground(new java.awt.Color(10, 64, 83));
        jComboBox3.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 12)); // NOI18N
        jComboBox3.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox3.setMaximumRowCount(3);
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All Orders", "Walk-ins", "Deliveries" }));

        generatebtn1.setBackground(new java.awt.Color(140, 208, 218));
        generatebtn1.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 12)); // NOI18N
        generatebtn1.setForeground(new java.awt.Color(34, 73, 87));
        generatebtn1.setText("Generate");

        editmodule2.setBackground(new java.awt.Color(140, 208, 218));
        editmodule2.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 12)); // NOI18N
        editmodule2.setForeground(new java.awt.Color(34, 73, 87));
        editmodule2.setText("Edit Module");

        javax.swing.GroupLayout completetransacLayout = new javax.swing.GroupLayout(completetransac);
        completetransac.setLayout(completetransacLayout);
        completetransacLayout.setHorizontalGroup(
            completetransacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completetransacLayout.createSequentialGroup()
                .addGroup(completetransacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(completetransacLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(pendingbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(completebtn2))
                    .addGroup(completetransacLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(completetransacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1076, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(completetransacLayout.createSequentialGroup()
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generatebtn1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editmodule2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(85, Short.MAX_VALUE))
        );
        completetransacLayout.setVerticalGroup(
            completetransacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completetransacLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(completetransacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(completebtn2)
                    .addComponent(pendingbtn2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(completetransacLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generatebtn1)
                    .addComponent(editmodule2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        tabcontent.add(completetransac, "card5");

        pendingdeliver.setBackground(new java.awt.Color(255, 255, 255));

        pendingdelivertbl.setBackground(new java.awt.Color(229, 229, 229));
        pendingdelivertbl.setForeground(new java.awt.Color(10, 64, 83));
        pendingdelivertbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Item/QTY", "Customer ID", "Name", "Address", "Price", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(pendingdelivertbl);

        pendingbtn3.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 36)); // NOI18N
        pendingbtn3.setForeground(new java.awt.Color(10, 64, 83));
        pendingbtn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingbtn3.setText("Pending");

        completebtn3.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 36)); // NOI18N
        completebtn3.setForeground(new java.awt.Color(10, 64, 83));
        completebtn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completebtn3.setText("Completed");

        jComboBox2.setBackground(new java.awt.Color(10, 64, 83));
        jComboBox2.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 12)); // NOI18N
        jComboBox2.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "On-Going" }));

        generatebtn2.setBackground(new java.awt.Color(140, 208, 218));
        generatebtn2.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 12)); // NOI18N
        generatebtn2.setForeground(new java.awt.Color(10, 64, 83));
        generatebtn2.setText("Generate");

        editmodule3.setBackground(new java.awt.Color(140, 208, 218));
        editmodule3.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 12)); // NOI18N
        editmodule3.setForeground(new java.awt.Color(34, 73, 87));
        editmodule3.setText("Edit Module");

        javax.swing.GroupLayout pendingdeliverLayout = new javax.swing.GroupLayout(pendingdeliver);
        pendingdeliver.setLayout(pendingdeliverLayout);
        pendingdeliverLayout.setHorizontalGroup(
            pendingdeliverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingdeliverLayout.createSequentialGroup()
                .addGroup(pendingdeliverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pendingdeliverLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(pendingbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(completebtn3))
                    .addGroup(pendingdeliverLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(pendingdeliverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pendingdeliverLayout.createSequentialGroup()
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generatebtn2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editmodule3, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1064, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        pendingdeliverLayout.setVerticalGroup(
            pendingdeliverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pendingdeliverLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(pendingdeliverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(completebtn3)
                    .addComponent(pendingbtn3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pendingdeliverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generatebtn2)
                    .addComponent(editmodule3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        tabcontent.add(pendingdeliver, "card2");
        pendingdeliver.getAccessibleContext().setAccessibleName("Invoices");

        completedeliver.setBackground(new java.awt.Color(255, 255, 255));

        pendingdelivertbl1.setBackground(new java.awt.Color(229, 229, 229));
        pendingdelivertbl1.setForeground(new java.awt.Color(10, 64, 83));
        pendingdelivertbl1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Item/QTY", "Customer ID", "Name", "Address", "Price", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Float.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane4.setViewportView(pendingdelivertbl1);

        pendingbtn4.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 36)); // NOI18N
        pendingbtn4.setForeground(new java.awt.Color(10, 64, 83));
        pendingbtn4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pendingbtn4.setText("Pending");

        completebtn4.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 36)); // NOI18N
        completebtn4.setForeground(new java.awt.Color(10, 64, 83));
        completebtn4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        completebtn4.setText("Completed");

        jComboBox4.setBackground(new java.awt.Color(10, 64, 83));
        jComboBox4.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 12)); // NOI18N
        jComboBox4.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pending", "On-Going" }));

        generatebtn3.setBackground(new java.awt.Color(140, 208, 218));
        generatebtn3.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 12)); // NOI18N
        generatebtn3.setForeground(new java.awt.Color(10, 64, 83));
        generatebtn3.setText("Generate");

        editmodule4.setBackground(new java.awt.Color(140, 208, 218));
        editmodule4.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 12)); // NOI18N
        editmodule4.setForeground(new java.awt.Color(34, 73, 87));
        editmodule4.setText("Edit Module");

        javax.swing.GroupLayout completedeliverLayout = new javax.swing.GroupLayout(completedeliver);
        completedeliver.setLayout(completedeliverLayout);
        completedeliverLayout.setHorizontalGroup(
            completedeliverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completedeliverLayout.createSequentialGroup()
                .addGroup(completedeliverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(completedeliverLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(pendingbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(completebtn4))
                    .addGroup(completedeliverLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(completedeliverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(completedeliverLayout.createSequentialGroup()
                                .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(generatebtn3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editmodule4, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1064, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        completedeliverLayout.setVerticalGroup(
            completedeliverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(completedeliverLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(completedeliverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(completebtn4)
                    .addComponent(pendingbtn4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(completedeliverLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(generatebtn3)
                    .addComponent(editmodule4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 462, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        tabcontent.add(completedeliver, "card2");

        authenticate.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 36)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(10, 64, 83));
        jLabel7.setText("Enter Password");

        authpassbtn.setBackground(new java.awt.Color(140, 208, 218));
        authpassbtn.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 14)); // NOI18N
        authpassbtn.setForeground(new java.awt.Color(34, 73, 87));
        authpassbtn.setText("Authenticate");
        authpassbtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(140, 208, 218), 1, true));

        authpass.setBackground(new java.awt.Color(229, 229, 229));
        authpass.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 24)); // NOI18N
        authpass.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(229, 229, 229), 1, true));

        javax.swing.GroupLayout authenticateLayout = new javax.swing.GroupLayout(authenticate);
        authenticate.setLayout(authenticateLayout);
        authenticateLayout.setHorizontalGroup(
            authenticateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, authenticateLayout.createSequentialGroup()
                .addContainerGap(467, Short.MAX_VALUE)
                .addGroup(authenticateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(authenticateLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel7))
                    .addComponent(authpass, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(authenticateLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(authpassbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(458, 458, 458))
        );
        authenticateLayout.setVerticalGroup(
            authenticateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authenticateLayout.createSequentialGroup()
                .addGap(208, 208, 208)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(authpassbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(324, Short.MAX_VALUE))
        );

        tabcontent.add(authenticate, "card6");

        authreports.setBackground(new java.awt.Color(255, 255, 255));

        jLabel17.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(10, 64, 83));
        jLabel17.setText("Reports");
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        genreport1.setBackground(new java.awt.Color(140, 208, 218));
        genreport1.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 14)); // NOI18N
        genreport1.setForeground(new java.awt.Color(34, 73, 87));
        genreport1.setText("Generate");
        genreport1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(140, 208, 218), 1, true));

        genreport2.setBackground(new java.awt.Color(140, 208, 218));
        genreport2.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 14)); // NOI18N
        genreport2.setForeground(new java.awt.Color(34, 73, 87));
        genreport2.setText("Generate");
        genreport2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(140, 208, 218), 1, true));
        genreport2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genreport2ActionPerformed(evt);
            }
        });

        genreport3.setBackground(new java.awt.Color(140, 208, 218));
        genreport3.setFont(new java.awt.Font("Source Sans Pro Semibold", 1, 14)); // NOI18N
        genreport3.setForeground(new java.awt.Color(34, 73, 87));
        genreport3.setText("Generate");
        genreport3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(140, 208, 218), 1, true));

        javax.swing.GroupLayout authreportsLayout = new javax.swing.GroupLayout(authreports);
        authreports.setLayout(authreportsLayout);
        authreportsLayout.setHorizontalGroup(
            authreportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, authreportsLayout.createSequentialGroup()
                .addContainerGap(342, Short.MAX_VALUE)
                .addComponent(genreport2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(113, 113, 113)
                .addGroup(authreportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addGroup(authreportsLayout.createSequentialGroup()
                        .addComponent(genreport1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(103, 103, 103)
                        .addComponent(genreport3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(341, 341, 341))
        );
        authreportsLayout.setVerticalGroup(
            authreportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(authreportsLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 266, Short.MAX_VALUE)
                .addGroup(authreportsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genreport1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genreport3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(genreport2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(229, 229, 229))
        );

        tabcontent.add(authreports, "card6");

        getContentPane().add(tabcontent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void invoicebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_invoicebtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_invoicebtnMouseClicked

    private void genreport2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genreport2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genreport2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel authenticate;
    private javax.swing.JLabel authenticbtn;
    private javax.swing.JPanel authentictab;
    private javax.swing.JPasswordField authpass;
    private javax.swing.JButton authpassbtn;
    private javax.swing.JPanel authreports;
    private javax.swing.JTextField brgyfield;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cityfield;
    private javax.swing.JLabel completebtn1;
    private javax.swing.JLabel completebtn2;
    private javax.swing.JLabel completebtn3;
    private javax.swing.JLabel completebtn4;
    private javax.swing.JPanel completedeliver;
    private javax.swing.JPanel completetransac;
    private javax.swing.JLabel deliverbtn;
    private javax.swing.JPanel delivertab;
    private javax.swing.JButton editmodule1;
    private javax.swing.JButton editmodule2;
    private javax.swing.JButton editmodule3;
    private javax.swing.JButton editmodule4;
    private javax.swing.JTextField fnamefield;
    private javax.swing.JPanel form;
    private javax.swing.JButton generatebtn;
    private javax.swing.JButton generatebtn1;
    private javax.swing.JButton generatebtn2;
    private javax.swing.JButton generatebtn3;
    private javax.swing.JButton genreport1;
    private javax.swing.JButton genreport2;
    private javax.swing.JButton genreport3;
    private javax.swing.JTextField housefield;
    private javax.swing.JLabel invoicebtn;
    private javax.swing.JPanel invoices;
    private javax.swing.JPanel invoicetab;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField lnamefield;
    private javax.swing.JPanel maintabs;
    private javax.swing.JTextField mobilefield;
    private javax.swing.JLabel pendingbtn1;
    private javax.swing.JLabel pendingbtn2;
    private javax.swing.JLabel pendingbtn3;
    private javax.swing.JLabel pendingbtn4;
    private javax.swing.JPanel pendingdeliver;
    private javax.swing.JTable pendingdelivertbl;
    private javax.swing.JTable pendingdelivertbl1;
    private javax.swing.JPanel pendingtransac;
    private javax.swing.JTable pendingtransactbl;
    private javax.swing.JTable pendingtransactbl1;
    private javax.swing.JPopupMenu popupmenu1;
    private javax.swing.JLabel productdesc;
    private javax.swing.JLabel productimg;
    private javax.swing.JLabel productimg1;
    private javax.swing.JLabel productname1;
    private javax.swing.JLabel productprice;
    private javax.swing.JSpinner productqty;
    private javax.swing.JToggleButton productselect;
    private javax.swing.JPanel qnb;
    private javax.swing.JRadioButton radiodeliver;
    private javax.swing.JRadioButton radiowalkin;
    private javax.swing.JPanel signout;
    private javax.swing.JLabel signoutbtn;
    private javax.swing.JButton submitform;
    private javax.swing.JPanel tabcontent;
    private javax.swing.JLabel transacbtn;
    private javax.swing.JPanel transactab;
    // End of variables declaration//GEN-END:variables
}
