/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package software1;

import glasspanepopup.GlassPanePopup;
import java.awt.event.ActionListener;
import java.util.Arrays;

/**
 *
 * @author 97433
 */
public class RegisterAuth extends javax.swing.JPanel {
    private char[] password;
    private char[] confpass;
    private final String username;
    private final String role;
    /**
     * Creates new form RegisterAuth
     * @param username
     * @param password
     */
    public RegisterAuth(String username, char[] password, char[] confpass, String role) {
        initComponents();
        this.password = password;
        password = null;
        this.confpass = confpass;
        confpass = null;
        this.username = username;
        this.role = role;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        authpass2 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(229, 229, 229));

        jLabel9.setFont(new java.awt.Font("Source Sans Pro Light", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(10, 64, 83));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Owner Authenticate");

        authpass2.setBackground(new java.awt.Color(255, 255, 255));
        authpass2.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 24)); // NOI18N
        authpass2.setForeground(new java.awt.Color(0, 0, 0));
        authpass2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        authpass2.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        jButton1.setText("Confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(150, 150, 150)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(47, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(authpass2)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(authpass2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Database db = new Database();
        try {
            if (!db.authenticate(String.valueOf(authpass2.getPassword()))) {
                // CODE FOR WRONG AUTHENTICATION PASS
                System.out.println("wrong auth");
                popupMsg("Wrong Authentication");
            }
            else if (db.checkUser(username)) {
                // CODE FOR USER ALREADY EXISTING
                System.out.println("existing user");
                popupMsg("Username Taken");
            }
            else if (!String.valueOf(password).equals(String.valueOf(confpass))) {
                // CODE FOR PASSWORDS DO NOT MATCH
                System.out.println("PASSWORDS DO NOT MATCH");
                popupMsg("PASSWORDS DO NOT MATCH");
            }
            else if (!db.addUser(username, String.valueOf(password), role)){ //TRY TO REGISTER USER
                // CODE FOR REGISTRATION ERROR IN SQL
                System.out.println("sql error");
                popupMsg("SQL error");
            }
            else {
                // REGISTER THE NEW USER SUCCESS CODE
                popupMsg("Register User Success");
            }
        } finally {
            db.closeConnection();
        }   
    }//GEN-LAST:event_jButton1ActionPerformed
    private void popupMsg(String msg) {
        GlassPanePopup.closePopupLast();
        GlassPanePopup.showPopup(new Message(msg));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField authpass2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
