package software1;
import java.awt.event.ActionListener;
import glasspanepopup.GlassPanePopup;
import java.awt.event.ActionEvent;
import javax.swing.JTextField;
import javax.swing.text.PlainDocument;

public class TransacEditPopup extends javax.swing.JPanel {
    private final String[] details;
    public TransacEditPopup(String[] details) {
        this.details = details;
        initComponents();
        PopOrderID.setEditable(false);
        PopItemQTY.setEditable(false);
        PopCustID.setEditable(false);
        PopName.setEditable(false);
        PopAddress.setEditable(false);
        PopPrice.setEditable(false);
        savebtn.setVisible(false);
        editbtn.setVisible(false);
        
        ((PlainDocument)PopPaid.getDocument()).setDocumentFilter(new MyFloatFilter());
        placeDetails();
        
        //setOpaque(false);
    }
    private void placeDetails() {
        PopOrderID.setText(this.details[0]);
        PopItemQTY.setText(this.details[1]);
        PopCustID.setText(this.details[2]);
        PopName.setText(this.details[3]);
        PopAddress.setText(this.details[4]);
        PopPrice.setText(this.details[5]);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PopPaid = new javax.swing.JTextField();
        removetrans = new javax.swing.JButton();
        confirmtrans = new javax.swing.JButton();
        editbtn = new javax.swing.JButton();
        savebtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        PopName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PopPrice = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        PopItemQTY = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        PopAddress = new javax.swing.JTextField();
        PopOrderID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        PopCustID = new javax.swing.JTextField();

        jPasswordField1.setText("jPasswordField1");

        setBackground(new java.awt.Color(229, 229, 229));

        jPanel2.setBackground(new java.awt.Color(229, 229, 229));
        jPanel2.setPreferredSize(new java.awt.Dimension(0, 125));

        jLabel1.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(34, 73, 87));
        jLabel1.setText("Enter Amount Paid:");

        removetrans.setBackground(new java.awt.Color(235, 89, 89));
        removetrans.setForeground(new java.awt.Color(34, 73, 87));
        removetrans.setText("Remove");
        removetrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removetransActionPerformed(evt);
            }
        });

        confirmtrans.setBackground(new java.awt.Color(140, 208, 218));
        confirmtrans.setForeground(new java.awt.Color(34, 73, 87));
        confirmtrans.setText("Confirm");
        confirmtrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmtransActionPerformed(evt);
            }
        });

        editbtn.setBackground(new java.awt.Color(34, 73, 87));
        editbtn.setForeground(new java.awt.Color(255, 255, 255));
        editbtn.setText("Cancel");
        editbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editbtnActionPerformed(evt);
            }
        });

        savebtn.setBackground(new java.awt.Color(34, 73, 87));
        savebtn.setForeground(new java.awt.Color(255, 255, 255));
        savebtn.setText("Save");
        savebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PopPaid, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(confirmtrans, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(removetrans, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmtrans, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removetrans, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopPaid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(savebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(229, 229, 229));

        PopName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PopFieldMouseClicked(evt);
            }
        });
        PopName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopNameActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(34, 73, 87));
        jLabel2.setText("Order ID");

        jLabel6.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(34, 73, 87));
        jLabel6.setText("Price");

        PopPrice.setMinimumSize(new java.awt.Dimension(70, 25));
        PopPrice.setPreferredSize(new java.awt.Dimension(70, 28));
        PopPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PopFieldMouseClicked(evt);
            }
        });
        PopPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopPriceActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(34, 73, 87));
        jLabel5.setText("Name");

        jLabel4.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(34, 73, 87));
        jLabel4.setText("Cust ID");

        PopItemQTY.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PopFieldMouseClicked(evt);
            }
        });
        PopItemQTY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopItemQTYActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(34, 73, 87));
        jLabel7.setText("Address");

        PopAddress.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PopFieldMouseClicked(evt);
            }
        });
        PopAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopAddressActionPerformed(evt);
            }
        });

        PopOrderID.setMinimumSize(new java.awt.Dimension(70, 25));
        PopOrderID.setPreferredSize(new java.awt.Dimension(70, 28));
        PopOrderID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PopFieldMouseClicked(evt);
            }
        });
        PopOrderID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopOrderIDActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(34, 73, 87));
        jLabel3.setText("Item/QTY");

        PopCustID.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PopFieldMouseClicked(evt);
            }
        });
        PopCustID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PopCustIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PopOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel3))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(PopItemQTY, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)
                        .addGap(72, 72, 72)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(89, 89, 89)
                        .addComponent(jLabel6)
                        .addGap(8, 8, 8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(PopCustID, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PopName, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PopAddress)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PopPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(36, 36, 36))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6)
                    .addComponent(jLabel3))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PopOrderID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopItemQTY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopCustID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PopPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 843, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void confirmtransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmtransActionPerformed
        ConfirmTransac obj = new ConfirmTransac();
        GlassPanePopup.showPopup(obj);
    }//GEN-LAST:event_confirmtransActionPerformed

    private void removetransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removetransActionPerformed
        RemoveTransac obj = new RemoveTransac();
        GlassPanePopup.showPopup(obj);
    }//GEN-LAST:event_removetransActionPerformed

    private void PopOrderIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopOrderIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PopOrderIDActionPerformed

    private void PopItemQTYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopItemQTYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PopItemQTYActionPerformed

    private void PopCustIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopCustIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PopCustIDActionPerformed

    private void PopNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PopNameActionPerformed

    private void PopAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PopAddressActionPerformed

    private void PopPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PopPriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PopPriceActionPerformed

    private void editbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editbtnActionPerformed
        
    }//GEN-LAST:event_editbtnActionPerformed

    private void savebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savebtnActionPerformed
        
    }//GEN-LAST:event_savebtnActionPerformed

    private void PopFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PopFieldMouseClicked
        JTextField field = (JTextField) evt.getComponent();
        System.out.println(field.getText());
        if (field == PopOrderID) GlassPanePopup.showPopup(new Message("Order ID is not editable"));
        else if (field == PopCustID) GlassPanePopup.showPopup(new Message("Customer ID is not editable"));
        else if (field == PopPrice) GlassPanePopup.showPopup(new Message("Price is automatically calculated"));
        else if (field == PopItemQTY) {
            
        }
        else {
            field.setEditable(true);
            editbtn.setVisible(true);
            savebtn.setVisible(true);
            jLabel1.setVisible(false);
            PopPaid.setVisible(false);
            confirmtrans.setVisible(false);
            removetrans.setVisible(false);
        }
    }//GEN-LAST:event_PopFieldMouseClicked
    public void editSave (ActionListener evt) {
        savebtn.addActionListener(event -> {
            SavePopup obj = new SavePopup();
            obj.save(evt);
            GlassPanePopup.showPopup(obj);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField PopAddress;
    private javax.swing.JTextField PopCustID;
    private javax.swing.JTextField PopItemQTY;
    private javax.swing.JTextField PopName;
    private javax.swing.JTextField PopOrderID;
    private javax.swing.JTextField PopPaid;
    private javax.swing.JTextField PopPrice;
    private javax.swing.JButton confirmtrans;
    private javax.swing.JButton editbtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton removetrans;
    private javax.swing.JButton savebtn;
    // End of variables declaration//GEN-END:variables
}
